#' Call LimeSurvey API
#'
#' This is the basic functio to call the LimeSurvey API for all documented
#' methods (see https://api.limesurvey.org/classes/remotecontrol-handle.html).
#'
#' For this to work, one has to set the environment variable `LIM_URL`, which is
#' accessible in the global configuration site at LimeSurvey after enabling the
#' JSON-PRC interface.
#'
#' @param method String, a method outlined in the API documentation
#' @param params List, needed parameters as outlined in the API documentation.
#' @param include_session_key Boolean, whether sesison key should be included.
#'   This is virtually always the case, except when the session key is
#'   generated, which is why this option is needed. If in doubt, don't touch it.
#' @param ignore_status Boolean, most of the time, a status indicates an error,
#'   but sometimes, the status message is actually useful information. This
#'   argument switches whether to stop if a status message was submitted or if
#'   to keep it.
#'
#' @return A `httr2` response object.
#' @export
lime_call_api <- function(
        method,
        params = NULL,
        include_session_key = TRUE,
        ignore_status = FALSE
) {
    # Include session key, essentially needed for every RCP call but not for key
    # generation
    if (include_session_key) {
        final_params <- c(
            list(sSessionKey = Sys.getenv("LIM_SESSION_KEY")),
            params
        )
    } else {
        final_params <- params
    }


    # The request itself. id = " " must be present, otherwise, the request would
    # throw an error
    lim_request <- httr2::request(Sys.getenv("LIM_URL")) |>
        httr2::req_body_json(
            list(
                method = method,
                params = final_params,
                id = " "
            )
        ) |>
        httr2::req_perform()


    if (ignore_status) {
        lim_request
    } else {
        # Abort further function calls if API results in a status message and show
        # that message (a status indicates an error)
        if (!.throws_error(lim_request)) {
            lim_request
        } else {
            cli::cli_abort(.get_error_message(lim_request))
        }
    }
}


#' Get results from a JSON formatted response
#'
#' Tidies the `httr2` response and pulls the results out of it.
#'
#' @param response A response as generated by `lime_call_api`
#'
#' @return A response
.get_results <- function(response) {
    response |>
        httr2::resp_body_json() |>
        purrr::pluck("result")
}


#' Get status message
#'
#' @inheritParams .get_results
#'
#' @return String.
.get_error_message <- function(response) {
    response |>
        .get_results() |>
        purrr::pluck("status")
}


#' Checks if status is not empty
#'
#' @inheritParams .get_results
#'
#' @return Boolean
.throws_error <- function(response) {
    !is.null(.get_error_message(response))
}
